require("plugins")
require("general")
require("luasnip-config")
require("cmp-config")
require("lsp-config")
require("telescope-config")
require("harpoon-config")
require("metals-config")
require("gitsigns-config")
require("lualine-config")
require("nvim_comment-config")
require('autopairs-config')
require('nvim-tree-config')
require("treesitter-config")
-- require("rainbow_delimiters-config")
require("context-config")
require("todo-comments-config")
require("colorschemes.catpuccin")
