require("general")
require("plugins")
require("luasnip-config")
require("cmp-config")
require("lsp-config")
require("treesitter-config")
require("telescope-config")
-- require("colorschemes.rose_pine-config")
require("colorschemes.catpuccin-config")
require("orgmode-config")
require("metals-config")
require("gitsigns-config")
require("lualine-config")
require("nvim_transparent-config")
require("nvim_comment-config")
require("toggleterm-config")
require('centerpad-config')
require('autopairs-config')
