vim.cmd('source $HOME/.config/nvim/modules/plugins.vim')
require('general')
require('lsp')
require('treesitter')
require('colorschemes.gruvbox')
require('telescope')
require('metals_config')

--vim.cmd('source $HOME/.config/nvim/modules/python.vim')
--vim.cmd('source $HOME/.config/nvim/modules/gitsigns.vim')
